AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: TEST RUST Lambda with API Gateway using SAM

Resources:
  RustTestLambda:
    Type: AWS::Serverless::Function
    Properties:
      Runtime: provided.al2023
      # See Makefile release-lambda script
      CodeUri: ../../target/release/aws_lambda
      Handler: lambda
      Architectures:
        - arm64
      Timeout: 30
      MemorySize: 256
      Policies:
        - AWSLambdaBasicExecutionRole
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
        HttpApiEventGreedy:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY

Outputs:
  WebEndpoint:
    Description: "API Gateway endpoint URL for HTTP API"
    Value: !Sub "https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/"
